config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :movies do
      resources :verdicts,  except: [:show, :index]
  end

  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base

  has_attached_file :image, styles: { medium: "400x600#"}, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :verdicts

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :verdicts, dependent: :destroy
end

app/models/verdict.rb
class Verdict < ActiveRecord::Base
    belongs_to :user
    belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin!, only: [:edit, :destroy, :new]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @verdicts = Verdict.where(movie_id: @movie.id).order("created_at DESC")

    if @verdicts.blank?
      @avg_verdict = 0
    else
      @avg_verdict = @verdicts.average(:rating).round(2)
    end
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:name, :year, :director, :cast, :synopsis, :image)
    end

    def authenticate_admin!
      if !current_user.try(:admin?)
        redirect_to root_path
      end
    end
end

app/controllers/verdicts_controller.rb
class VerdictsController < ApplicationController
  before_action :set_verdict, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :set_movie

  # GET /verdicts/new
  def new
    @verdict = Verdict.new
  end

  # GET /verdicts/1/edit
  def edit
  end

  # POST /verdicts
  # POST /verdicts.json
  def create
    @verdict = Verdict.new(verdict_params)
    @verdict.user_id = current_user.id
    @verdict.movie_id = @movie.id

    respond_to do |format|
      if @verdict.save
        format.html { redirect_to @movie, notice: 'Verdict was successfully created.' }
        format.json { render :show, status: :created, location: @verdict }
      else
        format.html { render :new }
        format.json { render json: @verdict.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /verdicts/1
  # PATCH/PUT /verdicts/1.json
  def update
    respond_to do |format|
      if @verdict.update(verdict_params)
        format.html { redirect_to @movie, notice: 'Verdict was successfully updated.' }
        format.json { render :show, status: :ok, location: @verdict }
      else
        format.html { render :edit }
        format.json { render json: @verdict.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /verdicts/1
  # DELETE /verdicts/1.json
  def destroy
    @verdict.destroy
    respond_to do |format|
      format.html { redirect_to movie_url, notice: 'Verdict was successfully destroyed.' }
      format.json { head :no_content }
    end
    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_verdict
      @verdict = Verdict.find(params[:id])
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def verdict_params
      params.require(:verdict).permit(:rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/verdicts_helper.rb
module VerdictsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "hammer.png", height: 50, width:50 %>
      <%= link_to "The Hammer", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        	<% if current_user.try(:admin?) %>
            	<li><%= link_to "New Movie", new_movie_path, class: "active" %></li>
		<% end %>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
        <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
            <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="shortcut icon" href="/assets/hammer.png"/>
  <title>The Hammer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
 </div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, html: { multipart: true }  do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :director %><br>
    <%= f.text_field :director %>
  </div>
  <div class="field">
    <%= f.label :cast %><br>
    <%= f.text_area :cast %>
  </div>
  <div class="field">
    <%= f.label :synopsis %><br>
    <%= f.text_area :synopsis %>
  </div>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<% if !user_signed_in? %>
    <div class="jumbotron">
      <h1>Verdicts for your favorite movies!</h1>
      <p>Created by João Paulo and João Vitor</p>
      <p><%= link_to "Sign Up to Review", new_user_registration_path, class: "btn btn-primary btn-lg" %></p>
    </div>
<% end %>

<div class="row">
  <% @movies.each do |movie| %>
          <div class="col-sm-6 col-md-3">
                  <div class="thumbnail">
                    <%= link_to (image_tag movie.image.url(:medium), class: 'image'), movie %>
                  </div>
          </div>
    <% end %>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @movie.image.url(:medium) %>
        <div class="star-rating" data-score= <%= @avg_verdict %> ></div>
        <em><%= "Based on #{@verdicts.length} verdicts" %></em>
        <div class="table-responsive">
          <table class="table">
            <tbody>
              <tr>
                <td><strong>Name:</strong></td>
                <td><%= @movie.name %></td>
              </tr>
              <tr>
                <td><strong>Year:</strong></td>
                <td><%= @movie.year %></td>
              </tr>
              <tr>
                <td><strong>Director:</strong></td>
                <td><%= @movie.director %></td>
              </tr>
              <tr>
                <td><strong>Cast:</strong></td>
                <td><%= @movie.cast.to_s %></td>
              </tr>
              <tr>
                <td><strong>Synopsis:</strong></td>
                <td><%= @movie.synopsis.to_s %></td>
              </tr>
            </tbody>
          </table>
          <%= link_to "Write Verdict", new_movie_verdict_path(@movie), class: "btn btn-default"%>
        </div>
      </div>
      <div class="col-md-7 col-md-offset-1">
        <h1 class="verdict_name"><%= @movie.name %></h1>
        <p><%= @movie.synopsis %></p>

        <% if @verdicts.blank? %>
          <h3>Give the first Verdict!</h3>
          <%= link_to "Write Verdict", new_movie_verdict_path(@movie), class: "btn btn-danger" %>
        <% else %>
          <% @verdicts.each do |verdict| %>
            <div class="verdicts">
              <div class="star-rating" data-score= <%= verdict.rating %> ></div>
              <p><%= verdict.comment %></p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if current_user.try(:admin?) %>
  <%= link_to 'Edit', edit_movie_path(@movie) , class: "btn btn-default" %> |
  <%= link_to 'Delete', @movie, method: :delete, class: "btn btn-default" , data: { confirm: 'Are you sure?' } %> |
<% end %>
<%= link_to 'Back', movies_path, class: "btn btn-default"  %>

<script>
    $('.star-rating').raty({
      path: '/assets/',
      readOnly: true,
      score: function() {
            return $(this).attr('data-score');
    }
  });
</script>

app/views/verdicts/_form.html.erb
<%= form_for([@movie, @verdict]) do |f| %>
  <% if @verdict.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@verdict.errors.count, "error") %> prohibited this verdict from being saved:</h2>

      <ul>
      <% @verdict.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id="star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
    path: '/assets/',
    scoreName: 'verdict[rating]'
  });
</script>

app/views/verdicts/edit.html.erb
<h1>Editing Verdict</h1>

<%= render 'form' %>

<%= link_to 'Back',  movie_path(@movie) %>

app/views/verdicts/new.html.erb
<h1>New Verdict</h1>

<%= render 'form' %>

<%= link_to 'Back', movie_path(@movie) %>